### ISSUE TITLE
Example not updated with new name of header

### ISSUE THREAD

**Issue by rboeije1** [beegee-tokyo/SHT1x-ESP#1]
As I could not get the SHT10 to work on the ESP32, I found your post. However, so far not much luck. Looking at the example, I guess you did not update it after you cloned the project? I expect the includefile should be 
#include <SHT1x-ESP.h>

not 
#include <SHT1x.h>

Anyway, I have compile warnings, I will post in separate issue. (And so far it is giving me -40,099C and -2.7%, but that might be on my side.

**Comment by rboeije1** [comment]
When I include your header, I get

In file included from C:\xxx\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32/esp32-hal.h:34:0,

                 from C:\xxx\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32/Arduino.h:35,

                 from C:\xxx\OneDrive\Documenten\Arduino\libraries\SHT1x_sensor_library_for_ESPx\SHT1x-ESP.cpp:17:

C:\xxx\OneDrive\Documenten\Arduino\libraries\SHT1x_sensor_library_for_ESPx\SHT1x-ESP.cpp: In member function 'uint16_t SHT1x::readRawData(SHT1x::ShtCommand, uint8_t, uint8_t) const':

C:\xxx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/include/newlib/math.h:57:34: warning: overflow in implicit constant conversion [-Woverflow]

 #  define NAN (__builtin_nanf(""))

                                  ^

C:\xxx\Documenten\Arduino\libraries\SHT1x_sensor_library_for_ESPx\SHT1x-ESP.cpp:107:10: note: in expansion of macro 'NAN'

   return NAN;

          ^

C:\xxx\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/include/newlib/math.h:57:34: warning: overflow in implicit constant conversion [-Woverflow]

 #  define NAN (__builtin_nanf(""))

                                  ^

C:\xxx\OneDrive\Documenten\Arduino\libraries\SHT1x_sensor_library_for_ESPx\SHT1x-ESP.cpp:111:10: note: in expansion of macro 'NAN'

   return NAN;

**Comment by beegee-tokyo** [comment]
About the header file, I forgot to update it. Will do in the next release.

For the compiler warnings I have to check. Didn't see them before. 

Do you have pull up resistors on the data and clock line of the sensor? The interface is similar to I2C and requires the pull ups. I am 6sing 10kOhm.

**Comment by rboeije1** [comment]
Hi Bernd, thanks. Yes I do have pull-ups. When I compile the example code (With the new header) it uploads, but it keeps on rebooting and spitting out 50 lines or so with false readings, as if the delay-function does not exists. (Even if I do not connect the SHT10) My board might be a bit instable, as I get MD5-errors as well every once in a while. (ESP32 core board v2) Will wait for other board. Also looks like it is very sensitive to what pins you are using. What pins do you use on the ESP32? Thanks and nice holidays!

 

Van: Bernd Giesecke <notifications@github.com> 
Verzonden: dinsdag 24 december 2019 12:29
Aan: beegee-tokyo/SHT1x-ESP <SHT1x-ESP@noreply.github.com>
CC: rene <github@rboeije.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [beegee-tokyo/SHT1x-ESP] Example not updated with new name of header (#1)

 

About the header file, I forgot to update it. Will do in the next release.

For the compiler warnings I have to check. Didn't see them before.

Do you have pull up resistors on the data and clock line of the sensor? The interface is similar to I2C and requires the pull ups. I am using 10kOhm.

**Comment by beegee-tokyo** [comment]
I am using usually [Adafruit Huzzah ESP32 Feather](https://www.adafruit.com/product/3405) boards. They are a little bit more expensive than the Chinese boards but very reliable. And I like the Adafruit concept of Feather MCUs and Wing extensions for fast prototyping.

The pins I use are the I2C default pins on the Feather board. Data = SDA = 23 and Clock = SCL = 22.

Not an excuse, but I didn't write the library complete by myself, the original is from DfRobots and I just made changes for ESP32 to it. 
That said, I found the reason for the NAN warning. It is a wrong return value in a library internal function. Will correct it in the next days.

**Comment by rboeije1** [comment]
This one comes from what I call a reliable source too. (Elektor if you know the magazine) I know you took a copy of the other one, I came to your version after searching and finding a  lot of people have the same issue and many solutions that might work or not. (https://github.com/espressif/arduino-esp32/issues/1064)  <https://github.com/espressif/arduino-esp32/issues/1064)%20>  So I was hopeful. Many thanks for the swift replies so far!

 

Van: Bernd Giesecke <notifications@github.com> 
Verzonden: dinsdag 24 december 2019 13:46
Aan: beegee-tokyo/SHT1x-ESP <SHT1x-ESP@noreply.github.com>
CC: rene <github@rboeije.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [beegee-tokyo/SHT1x-ESP] Example not updated with new name of header (#1)

 

I am using usually Adafruit Huzzah ESP32 Feather <https://www.adafruit.com/product/3405>  boards. They are a little bit more expensive than the Chinese boards but very reliable. And I like the Adafruit concept of Feather MCUs and Wing extensions for fast prototyping.

The pins I use are the I2C default pins on the Feather board. Data = SDA = 23 and Clock = SCL = 22.

Not an excuse, but I didn't write the library complete by myself, the original is from DfRobots and I just made changes for ESP32 to it.
That said, I found the reason for the NAN warning. It is a wrong return value in a library internal function. Will correct it in the next days.

**Comment by rboeije1** [comment]
Well, I finally decided to load a trimmed version of my project to a esp32 pico V4, that is running my other sensors an uploading mqtt data for some time, but is doesn't want to eat the SHT-code either.
 The loop is as simple as 
```

void loop()
{

#ifdef SHT10PRESENT
  float temp_c;
  float humidity;
 
  // Read values from the sensor
  temp_c = sht1x.readTemperatureC();
  humidity = sht1x.readHumidity();
 
  // Print the values to the serial port
  Serial.printf(" ** Temperature sens1: %5.1f, Humidity: 5.1f\%\n", temp_c, humidity);
#endif

  delay(1000);
}

```
Note: I notice I forgot the '%' in the format string (%5.1f), but that was due to trimming the code too fast before posting it here. 
the output is

```
Starting up
 ** Temperature sens1: -40.1, Humidity: 5.1f
 ** Temperature sens1: -40.1, Humidity: 5.1f
 ****** this lines repeated 80 times within a second or so..
 ** Temperature sens1: -40.1, Humidity: 5.1f
 ** TemperGuru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Core 1 register dump:
PC      : 0x400d2151  PS      : 0x00060b34  A0      : 0x800d12dc  A1      : 0x3ffb1ea0  
A2      : 0x3ffbebe8  A3      : 0x3ffb1f26  A4      : 0x3ffb1f49  A5      : 0x3f400fd4  
A6      : 0x80000000  A7      : 0x80000000  A8      : 0xe47fc000  A9      : 0x3ff40000  
A10     : 0x0000007f  A11     : 0x00000000  A12     : 0x3ffb8214  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x00000009  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x400029ac  LEND    : 0x400029cb  LCOUNT  : 0x00000000  

Backtrace: 0x400d2151:0x3ffb1ea0 0x400d12d9:0x3ffb1ec0 0x400d1526:0x3ffb1ee0 0x400d0c44:0x3ffb1f80 0x400d25b1:0x3ffb1fb0 0x4008822d:0x3ffb1fd0

Core 0 register dump:
PC      : 0x400e999e  PS      : 0x00060134  A0      : 0x800d471a  A1      : 0x3ffbbff0  
A2      : 0x00000000  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x00060120  A7      : 0x00000000  A8      : 0x800d42e2  A9      : 0x3ffbbfc0  
A10     : 0x00000000  A11     : 0x40084d90  A12     : 0x00060120  A13     : 0x3ffbb970  
A14     : 0x00000000  A15     : 0x3ffbbce0  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x400e999e:0x3ffbbff0 0x400d4717:0x3ffbc010 0x4008976e:0x3ffbc030 0x4008822d:0x3ffbc050

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
Starting up
 ** Temperature sens1: -40.1, Humidity: 5.1f
 ** Temperature sens1: -40.1, Humidity: 5.1f
 ** Temperature sens1: -40.1, Humidity: 5.1f

```

**Comment by beegee-tokyo** [comment]
I made a quick test with my Adafruit ESP32 Feather and it works just fine.
![20191227_113058](https://user-images.githubusercontent.com/512690/71499754-fba31680-289c-11ea-8ecb-a05e61f52842.jpg)
Code is basically the example code. clk line is connected to SCL (22) of the Feather, data line is connected to SDA (23) of the Feather. Both lines have a 1kOhm pullup to 3.3V

Code:
```cpp
/**
 * ReadSHT1xValues
 *
 * Read temperature and humidity values from an SHT1x-series (SHT10,
 * SHT11, SHT15) sensor.
 *
 * Copyright 2009 Jonathan Oxer <jon@oxer.com.au>
 * www.practicalarduino.com
 */

#include <Arduino.h>

#include <SHT1x-ESP.h>

// Specify data and clock connections and instantiate SHT1x object
#define dataPin  4
#define clockPin 5

// default to 5.0v boards, e.g. Arduino UNO
SHT1x sht1x(SDA, SCL, SHT1x::Voltage::DC_3_3v);

// if 3.3v board is used
//SHT1x sht1x(dataPin, clockPin, SHT1x::Voltage::DC_3_3v);

void setup()
{
  Serial.begin(115200); // Open serial connection to report values to host
  Serial.println("Starting up");
}

void loop()
{
  float temp_c;
  float temp_f;
  float humidity;

  // Read values from the sensor
  temp_c = sht1x.readTemperatureC();
  temp_f = sht1x.readTemperatureF();
  humidity = sht1x.readHumidity();

  // Print the values to the serial port
  Serial.printf("Temperature: %.2fC / %.2fF - Humidity %.2f%\n", temp_c, temp_f, humidity);

  delay(2000);
}
```
Log output
```log
Starting up
Temperature: 31.10C / 88.02F - Humidity 69.39
Temperature: 31.13C / 88.09F - Humidity 69.24
Temperature: 31.14C / 88.06F - Humidity 69.06
Temperature: 31.15C / 88.11F - Humidity 69.00
Temperature: 31.16C / 88.11F - Humidity 68.88
Temperature: 31.15C / 88.11F - Humidity 68.70
Temperature: 31.16C / 88.13F - Humidity 68.58
Temperature: 31.17C / 88.13F - Humidity 68.55
Temperature: 31.17C / 88.15F - Humidity 68.58
Temperature: 31.18C / 88.16F - Humidity 68.67
Temperature: 31.19C / 88.16F - Humidity 68.73
Temperature: 31.19C / 88.15F - Humidity 68.67
Temperature: 31.20C / 88.20F - Humidity 68.58
Temperature: 31.20C / 88.18F - Humidity 68.49
Temperature: 31.20C / 88.20F - Humidity 68.49
Temperature: 31.21C / 88.22F - Humidity 68.61
Temperature: 31.21C / 88.22F - Humidity 68.71
Temperature: 31.23C / 88.24F - Humidity 68.74
Temperature: 31.23C / 88.22F - Humidity 68.71
Temperature: 31.22C / 88.24F - Humidity 68.59
Temperature: 31.22C / 88.25F - Humidity 68.40
Temperature: 31.23C / 88.25F - Humidity 68.47
Temperature: 31.24C / 88.27F - Humidity 68.35
Temperature: 31.25C / 88.25F - Humidity 68.10
Temperature: 31.25C / 88.27F - Humidity 67.92
Temperature: 31.25C / 88.29F - Humidity 67.86
Temperature: 31.25C / 88.29F - Humidity 67.83
Temperature: 31.25C / 88.29F - Humidity 67.76
Temperature: 31.25C / 88.29F - Humidity 67.83
Temperature: 31.26C / 88.31F - Humidity 68.01
Temperature: 31.27C / 88.33F - Humidity 68.04
Temperature: 31.26C / 88.33F - Humidity 67.95
Temperature: 31.27C / 88.34F - Humidity 67.80
Temperature: 31.28C / 88.34F - Humidity 67.74
```

**Comment by rboeije1** [comment]
Hi Bernd, I was surprised that your example worked without any issue, but looking carefully at the differences between your and my code, I first was surprised to see pin 4 and 5, but immediately  noticed you use SDA and SCL constants, so that was as expected. I was not aware of the constants SDA and SCL, and I had an error in the pinnumbers, so when I made that change, my example worked as well. However, integrating that minor issue in my complete project, it still crashes as soon as I enable the code for SHT. By disabling the other sensors one by one, I found that there is a conflict with the adafruit BME680 sensor (Well, at least the driver). That one is also connected to the I2C bus. Even if I only share the clock pin and use 23 as pin for the data, is does no longer crash, but the BME is not able to read data. Using pin 18 as clockpin does not resolve the issue. So I will try other BME680 library, I found  <https://github.com/gschorcht/bme680-esp-idf> https://github.com/gschorcht/bme680-esp-idf, it is not in the standard Arduino list, but the readme looks well documented. 

Thanks for all your help, at least the SHT is working😊.

 

Van: Bernd Giesecke <notifications@github.com> 
Verzonden: vrijdag 27 december 2019 04:41
Aan: beegee-tokyo/SHT1x-ESP <SHT1x-ESP@noreply.github.com>
CC: rene <github@rboeije.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [beegee-tokyo/SHT1x-ESP] Example not updated with new name of header (#1)

 

I made a quick test with my Adafruit ESP32 Feather and it works just fine.
 <https://user-images.githubusercontent.com/512690/71499754-fba31680-289c-11ea-8ecb-a05e61f52842.jpg> 
Code is basically the example code. clk line is connected to SCL (22) of the Feather, data line is connected to SDA (23) of the Feather. Both lines have a 1kOhm pullup to 3.3V

Code:

/**
 * ReadSHT1xValues
 *
 * Read temperature and humidity values from an SHT1x-series (SHT10,
 * SHT11, SHT15) sensor.
 *
 * Copyright 2009 Jonathan Oxer <jon@oxer.com.au <mailto:jon@oxer.com.au> >
 * www.practicalarduino.com <http://www.practicalarduino.com> 
 */
 
#include <Arduino.h>
 
#include <SHT1x-ESP.h>
 
// Specify data and clock connections and instantiate SHT1x object
#define dataPin  4
#define clockPin 5
 
// default to 5.0v boards, e.g. Arduino UNO
SHT1x sht1x(SDA, SCL, SHT1x::Voltage::DC_3_3v);
 
// if 3.3v board is used
//SHT1x sht1x(dataPin, clockPin, SHT1x::Voltage::DC_3_3v);
 
void setup()
{
  Serial.begin(115200); // Open serial connection to report values to host
  Serial.println("Starting up");
}
 
void loop()
{
  float temp_c;
  float temp_f;
  float humidity;
 
  // Read values from the sensor
  temp_c = sht1x.readTemperatureC();
  temp_f = sht1x.readTemperatureF();
  humidity = sht1x.readHumidity();
 
  // Print the values to the serial port
  Serial.printf("Temperature: %.2fC / %.2fF - Humidity %.2f%\n", temp_c, temp_f, humidity);
 
  delay(2000);
}

Log output

Starting up
Temperature: 31.10C / 88.02F - Humidity 69.39
Temperature: 31.13C / 88.09F - Humidity 69.24
Temperature: 31.14C / 88.06F - Humidity 69.06
Temperature: 31.15C / 88.11F - Humidity 69.00
Temperature: 31.16C / 88.11F - Humidity 68.88
Temperature: 31.15C / 88.11F - Humidity 68.70
Temperature: 31.16C / 88.13F - Humidity 68.58
Temperature: 31.17C / 88.13F - Humidity 68.55
Temperature: 31.17C / 88.15F - Humidity 68.58
Temperature: 31.18C / 88.16F - Humidity 68.67
Temperature: 31.19C / 88.16F - Humidity 68.73
Temperature: 31.19C / 88.15F - Humidity 68.67
Temperature: 31.20C / 88.20F - Humidity 68.58
Temperature: 31.20C / 88.18F - Humidity 68.49
Temperature: 31.20C / 88.20F - Humidity 68.49
Temperature: 31.21C / 88.22F - Humidity 68.61
Temperature: 31.21C / 88.22F - Humidity 68.71
Temperature: 31.23C / 88.24F - Humidity 68.74
Temperature: 31.23C / 88.22F - Humidity 68.71
Temperature: 31.22C / 88.24F - Humidity 68.59
Temperature: 31.22C / 88.25F - Humidity 68.40
Temperature: 31.23C / 88.25F - Humidity 68.47
Temperature: 31.24C / 88.27F - Humidity 68.35
Temperature: 31.25C / 88.25F - Humidity 68.10
Temperature: 31.25C / 88.27F - Humidity 67.92
Temperature: 31.25C / 88.29F - Humidity 67.86
Temperature: 31.25C / 88.29F - Humidity 67.83
Temperature: 31.25C / 88.29F - Humidity 67.76
Temperature: 31.25C / 88.29F - Humidity 67.83
Temperature: 31.26C / 88.31F - Humidity 68.01
Temperature: 31.27C / 88.33F - Humidity 68.04
Temperature: 31.26C / 88.33F - Humidity 67.95
Temperature: 31.27C / 88.34F - Humidity 67.80
Temperature: 31.28C / 88.34F - Humidity 67.74

**Comment by beegee-tokyo** [comment]
I am happy I could help.

Using the same GPIO as clk for the I2C device and the sht10 might be the problem. Everytime your code talks to the sht10 the bme680 is listening as well. As the sht10 protocol is different from I2C, the bme680 might get confused. And when you talk to the bme680, the sht10 might try to answer as well.

The library should work on any other GPIO as clk and data, so if you have 2 free pins, you can try to connect the sht10 to different pins.
