### ISSUE TITLE
Handling disconnected probes

### ISSUE THREAD

**Issue by ghoeffner** [beegee-tokyo/SHT1x-ESP#3]
Hey there,

it would be great if disconnected probes would not trigger the wdt and cause a restart, but instead there is a way to figure out that a probe has been disconnected/is absent. 

In my particular use-case I want to detach and re-attach sensors on the fly and a probe-node might only have one sensor but has two ports.

Thanks!

**Comment by beegee-tokyo** [comment]
Sorry for late reply. Development has stopped on this library. I do not own these sensors anymore.
